# Generated by Django 3.2.12 on 2022-02-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_pretalx_permissions_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='redirect_on_invalid_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
